### ISSUE TITLE
Funkar inte..

### ISSUE THREAD

**Issue by jkohlin** [zombiefredrik/ludum34#1]
Behöver man göra nåt för att PlayerCube ska komma iväg? 
Vad jag förstår av scripten hoppar man med vänster, dashar med höger och Switchar? med båda. 

Jag får ett felmeddelande när spelet startar, kanske är därför det inte funkar här?

"NullReferenceException: Object reference not set to an instance of an object
PlayerMovement.Update () (at Assets/Scripts/PlayerMovement.cs:43)"
gales denna rad: ScoreText.text = Score.ToString();

**Comment by kebabskal** [comment]
Testa scenen "Segments" istället! :)

sön 13 dec. 2015 kl 19:12 skrev Johan notifications@github.com:

**Comment by jkohlin** [comment]
Aha Grymt!!
