### ISSUE TITLE
Om man bygger skiten och försöker spela så får man balla buggar. Verkar vara relaterat till image effects. Utreder

### ISSUE THREAD

**Issue by kebabskal** [zombiefredrik/ludum34#2]

**Comment by kebabskal** [comment]
Typ löst. Deferred pipeline och Linear istället för Gamma. Verkar funka på OSX iaf.

**Comment by jkohlin** [comment]
Var det "suddet" i högerkant du menade. Det fick jag enbart inne i Unity, men inte när jag byggde den. Däremot vet jag inte hur jag får den i widescreen så att poängen syns.
